name: InvTools
main: net.TheDgtl.InvTools.InvTools
version: 1.3.1
permissions:
  invtools.allowtools:
    description: Allow invincible tools
    default: true
  invtools.allowarmor:
    description: Allow invincible armor
    default: true